version: "3.8"

services:
  my-app:
    image: dharmakhadka/testapp
    ports:
    - 5050:5050
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOTUSERNAME: dharma
      MONGO_INITDB_ROOTPASSWORD: dharma

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081 
    environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: dharma
     ME_CONFIG_MONGODB_ADMINPASSWORD: dharma
